# Generated by Django 3.2.2 on 2021-05-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fusce', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('place', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('beautiful1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('beautiful2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('beautiful3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('beautiful4', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
