# Generated by Django 3.2.2 on 2021-05-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page2_img1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('page2_img2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('page3_img1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('page3_img2', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('page3_img3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('page3_img4', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
